name: PR Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    name: Check NixOS Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake
        run: nix flake check --all-systems --no-build

      - name: Check flake metadata
        run: nix flake metadata

      - name: Check formatting
        run: |
          nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ."

      - name: Build NixOS configuration (dry-run)
        run: |
          nix build .#nixosConfigurations.sauls-laptop.config.system.build.toplevel --dry-run

      - name: Evaluate configuration
        run: |
          nix eval .#nixosConfigurations.sauls-laptop.config.system.build.toplevel --apply 'x: "OK"'
